### ISSUE TITLE
Cutoff search text on Firefox

### ISSUE THREAD

**Issue by bhc24** [hacsoc/the_jolly_advisor#115]
Autocomplete text on Course Explorer is cutoff for users on Firefox

**Comment by a-johnston** [comment]
afaik this can be fixed by changing 'padding: 5px;' to 'padding: 0px 5px;'

**Comment by bhc24** [comment]
Thank you! I've been trying to get this fixed but I'm having some issues with my VM.

**Comment by ajm188** [comment]
Should have been closed a while ago.
