### ISSUE TITLE
Suggestion: Clickable course links within course description?

### ISSUE THREAD

**Issue by brenns10** [hacsoc/the_jolly_advisor#120]
Some courses don't actually have prerequisites, but they do list recommended participation in their description (eg. [EECS 458](http://advise.case.edu/courses/EECS458)).  It would be rather neat if there were some sort of regex matching and hyperlinking to courses titles within course descriptions.  Although, as Tekin mentioned, it's important to keep it general so that the app works with other types of course naming/numbering schemes.

Anyway, it's just a thought.  Shoot me down if you don't like it :)

**Comment by ajm188** [comment]
I agree it would be neat, but with the course select in the navbar, would it really add that much utility?

**Comment by brenns10** [comment]
I mean, they would add just as much utility as the clickable links in the Prerequisites section.  I don't think it's about utility as much as it is about consistency.  It's one of those things where (user story incoming) "As a user, I expect that if some course names are clickable, all of them should be."  Inconsistencies like that make interfaces more difficult for a user.

**Comment by ajm188** [comment]
Ok, I can get behind that.
