### ISSUE TITLE
"About" link does nothing

### ISSUE THREAD

**Issue by matthewbentley** [hacsoc/the_jolly_advisor#123]
In the user drop down menu there is an "about" button.  It doesn't do anything.

**Comment by ajm188** [comment]
Do you think it should link to something (and if so, what), or be removed?

**Comment by ajm188** [comment]
According to @StephHippo, the about page was originally supposed to have information about the Jolly Team, origin of the name, etc. So someone should probably do that.

**Comment by StephHippo** [comment]
Andrew has a PR open for this, but I'm having trouble upgrading to 2.2.2 on my local machine. Someone should take a look at this. I'd recommend checking out the branch and spinning it up.
