### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by matthewbentley** [hacsoc/the_jolly_advisor#130]
What is this licensed under?  Also, I know the copyright on the footer is fun, but should it be something more serious?

**Comment by matthewbentley** [comment]
Technically, we need permission from each contributor before chagning (in this case adding) a LICENSE.

If everyone who has contributed can comment below that they are OK with the MIT Licence, I can add it.  I will track down people who don't comment soon-ish.

**Comment by ajm188** [comment]
Fine by me.

@StephHippo @Aaronneyer @bhc24 @ReDaCtD ?

**Comment by StephHippo** [comment]
Ok here.

**Comment by Aaronneyer** [comment]
:+1:

**Comment by ReDaCtD** [comment]
Fine by me and my remarkable commitments

**Comment by bhc24** [comment]
I'm more than okay with it.

**Comment by matthewbentley** [comment]
Great!  That looks like everyone.  Expect a pull request soon.
And for the record I'm fine w/ MIT license, for my ~3 lines.
