### ISSUE TITLE
`first_professor` should actually try to find a professor, rather than just looking at the first one.

### ISSUE THREAD

**Issue by ajm188** [hacsoc/the_jolly_advisor#131]

**Comment by StephHippo** [comment]
Where does this get affected in the app on the user-end? Change seems fine, but I don't understand what we're changing.

**Comment by ajm188** [comment]
Some courses have their first professor as "Staff" or "TBA" even though they have other professors that are "real". So on the course show page, it will show "Staff" for the main professor even though we totally have a better professor to show.

Change is [here](https://github.com/hacsoc/the_jolly_advisor/blob/first-professor/app/helpers/courses_helper.rb#L3)

**Comment by ajm188** [comment]
As a side note, I'm using that `real_professors` method in the tips and reviews stuff (PR coming soon), so I want that to stay regardless.
