### ISSUE TITLE
Make SISImporter run daily

### ISSUE THREAD

**Issue by ajm188** [hacsoc/the_jolly_advisor#145]
Even easier once #144 is done

**Comment by StephHippo** [comment]
Can probably just use the whenever gem. It has a DSL for cron jobs. Makes it easy to generate for docker files as well.

**Comment by ajm188** [comment]
This was my plan. There is one small issue, being that we need to run the cron daemon and the rails server inside the container.

We could use supervisor to manage both processes, but the entry point for the rails:onbuild Dockerfile (which we inherit from) already sets its own entrypoint, and I'm not sure what happens if you set another. I think it overrides, in which case we would be fine. But, rails:onbuild also installs a bunch of cruft that we don't actually need, notably things like nodejs, and mysql, plus it doesn't let us run our app behind something like unicorn.

I think I'm going to write a more custom Dockerfile for us, which will fix both issues.

**Comment by matthewbentley** [comment]
I see three options:
1. Run some cron daemon in the jolly container (I'm not a big fan of this, docker is designed to be one process per container)
2. Run it in a separate container (containers are cheap, so it won't take any extra resources)
3. Run it from con on the host (last resort)

Number 2 would be a lot easier if / when we get docker-compose working on docker.case.edu.

**Comment by ajm188** [comment]
I was thinking something along the lines of either
1. with something like supervisord or god to manage both rails and the cron
2. with docker compose
3. not a fan

**Comment by thomasrussellmurphy** [comment]
As a note, production Jolly Advisor advertises this as a current feature: http://advise.case.edu/faq

**Comment by StephHippo** [comment]
This is something that should be realistically feasible to get going before the semester.
