### ISSUE TITLE
calling `rake scrape` with no arguments should not work

### ISSUE THREAD

**Issue by ajm188** [hacsoc/the_jolly_advisor#151]
this currently seems to work until the scraper tries to log in to SIS with the "provided" credentials. I should get yelled at much harder for using the command wrong.

**Comment by StephHippo** [comment]
BAD ANDREW

**Comment by StephHippo** [comment]
Is that enough?

**Comment by ajm188** [comment]
I think we'd prefer to let the machines do it #bowtoyourcompturoverlords
