### ISSUE TITLE
Does Case ID handling handle 4 digit IDs properly?

### ISSUE THREAD

**Issue by matthewbentley** [hacsoc/the_jolly_advisor#162]
Apparently those are a thing now

**Comment by ajm188** [comment]
Based on [this](https://github.com/hacsoc/the_jolly_advisor/blob/master/app/models/user.rb), we should be fine. We don't actually validate the case ID ourselves, we let CAS do that, and we only store it if they authenticate successfully. I forgot that was a thing.
