### ISSUE TITLE
Missing Economics 376

### ISSUE THREAD

**Issue by Aghassi** [hacsoc/the_jolly_advisor#166]
It would seem Economics 376 is not being scraped by Jolly Advisor. Not sure why, because it has most all my other classes. Economics 376 is listed on SIS too.

**Comment by ajm188** [comment]
Do you know when it was added? Or how long it has been there?
The update script _should_ be running every morning.

**Comment by Aghassi** [comment]
It has been in the system since at least last semester because I signed up for it last semester. It has been in the system since fall of last year (that was the first time they offered it). I know the script should update it, which is why I posted here.

**Comment by ajm188** [comment]
http://advise.case.edu/courses/ECON376

Looks like this is no longer an issue.

**Comment by Aghassi** [comment]
Yes but this class is not showing up in the calendar search box... so I can't add it to my calendar.

**Comment by ajm188** [comment]
![screen shot 2015-08-25 at 8 09 52 pm](https://cloud.githubusercontent.com/assets/4276638/9482741/47cff498-4b65-11e5-82ec-e5a88f145ee4.png)

**Comment by Aghassi** [comment]
Figures it starts working as soon as I posted that. Thanks =p

**Comment by ajm188** [comment]
Glad I could be of service! _continues to do nothing_
