### ISSUE TITLE
Spring 2016 data

### ISSUE THREAD

**Issue by zwh2** [hacsoc/the_jolly_advisor#177]
No data for spring 2016 classes.

**Comment by ajm188** [comment]
As far as I'm aware, the importer is still running nightly.

Running it locally, I am seeing courses from 2016 come in. cc-ing @matthewbentley to check on the status of the nightly import job.

**Comment by matthewbentley** [comment]
It should run a 4:30am every day.  I'll set up some logging and see what happens tomorrow.

**Comment by JKobyP** [comment]
I'm definitely not seeing anything - on the scheduler, no option for scheduling out to Spring '16 exists. Classes like Databases haven't changed to reflect that there's a section open in the Spring.

**Comment by zwh2** [comment]
@matthewbentley Any update?

**Comment by matthewbentley** [comment]
Fixed.  I'm closing this and opening a new issue regarding why this didn't happen automatically.
