### ISSUE TITLE
Courses don't show up on scheduler

### ISSUE THREAD

**Issue by JKobyP** [hacsoc/the_jolly_advisor#205]
To reproduce:

1. Go to advise.case.edu/scheduler
2. Add a course
3. Observe that the schedule remains blank

It seems that the courses _are_ being selected, because once you've "added" a course they disappear from the list. But the events do not show up on the schedule.

**Comment by ajm188** [comment]
I am also seeing this behavior in both chrome and firefox. Not sure what the issue is yet.

**Comment by JKobyP** [comment]
I'm no longer observing this

**Comment by ajm188** [comment]
Welp, let's close it for now! 😛
