### ISSUE TITLE
New semester apparently not scraped from SIS

### ISSUE THREAD

**Issue by JKobyP** [hacsoc/the_jolly_advisor#228]
On SIS, Spring 2017 data is up. On the scheduler, Spring 2017 data is not found.

**Comment by ajm188** [comment]
@JKobyP the sis importer reads from [here](http://case.edu/projects/erpextract/soc.xml) which does not have the 2017 data yet. There is a bit of delay between when the data is available in SIS proper and when the data is available in the SIS data dump.

Closing as invalid.
