### ISSUE TITLE
Doesn't load, or at least not off campus

### ISSUE THREAD

**Issue by snood1205** [hacsoc/the_jolly_advisor#231]
This might be a temporary problem, but as of right now, I cannot load this using an off campus IP Address. I'm not currently on campus so I'm not sure if it works on campus, but it's timing out. Here's basic information of my system:

```
OS Type,OS Version,Browser Type,IP Address,Javascript Enabled,Cookies Enabled,Color Depth,Screen Resolution,Browser Window Size,Flash Version,User Agent
Macintosh,OS X 10.11,Firefox,108.52.209.253,Yes,Yes,24,1280 x 800,1280 x 694,21.0.-1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0

```

**Comment by matthewbentley** [comment]
This is due to not having a firewall exception.  Right now you can access it through the VPN, or tunneling through people.acm.case.edu.  I'll see what I can do about opening up a port to the world.

**Comment by snood1205** [comment]
Thank you! I wasn't sure if this was intentional or not.

**Comment by ajm188** [comment]
Oh, looks like my email reply never made it through. Thanks for looking into this @matthewbentley .

**Comment by ajm188** [comment]
Hi, thanks for reporting!

I'm not sure why you're including this massive `phpinfo` dump - it doesn't
seem at all relevant and is quite noisy.

@matthewbentley can you see if this is an on-campus issue as well, or just
isolated to off-campus?

tor. 17. nov. 2016 kl. 09.11 skrev Eli Sadoff <notifications@github.com>:

**Comment by ajm188** [comment]
@snood1205 it seems to me that @matthewbentley resolved your issue, so I'm going to close this. Feel free to re-open if you disagree
