### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by ajm188** [hacsoc/the_jolly_advisor#247]
Let's encrypt, yo.

@matthewbentley preemptively assigning to you; figured you would be interested. If you don't want to take this, feel free to unassign

**Comment by matthewbentley** [comment]
This is on my longer term todo list for things running in docker on the acm server.

Right now, for each service it creates an interface w/ the proper MAC to get the required hostname, and then puts that interface into the container.

I'd like to have all these interfaces on the main VM and then use nginx to reverse proxy to each app container depending on the hostname.

This would give us the opportunity to serve multiple sites per interface (/ip address) and get lets encrypt certs for each site.

So I'll see if I can get around to this some time this or next week.

**Comment by ajm188** [comment]
Cool! Lemme know if there's anything you need from me for this.

**Comment by ajm188** [comment]
bump :)

**Comment by thomasrussellmurphy** [comment]
No longer deployed under this infrastructure (RIP krall) so closing.
