### ISSUE TITLE
Wishlist still getting undefined method schedulable? for nil class

### ISSUE THREAD

**Issue by StephHippo** [hacsoc/the_jolly_advisor#60]
Data is definitely there because it's showing up in Search and lets you navigate to the course show page.

When trying to add a course to a wishlist from the show page, it's erroring out like this with a NoMethodError.

It's possible that hitting "Add to Wishlist" isn't actually adding to WishList but further investigation needed.

**Comment by ajm188** [comment]
Looks like what's happening is in the `add_course` action of the WishlistController, `params[:course_id]` is nil.

If you look at the view (wishlist/index.html.haml), that autocomplete is supposed to take the id of the thing that was selected and populate it into the hidden course_id field. This isn't happening for reason. Not sure if someone touched that JS in all the PRs tonight.

**Comment by ajm188** [comment]
Closed by #93
