### ISSUE TITLE
Coveralls could use some more configuring

### ISSUE THREAD

**Issue by ajm188** [hacsoc/the_jolly_advisor#62]
It's doing coverage analysis on a lot of files that it shouldn't... namely the entire config/ and spec/ directories

**Comment by StephHippo** [comment]
How can you tell? I'm looking at the coverage/index.html and it looks like it's appropriately testing.

**Comment by ajm188** [comment]
This is how I can tell:
![screen shot 2015-04-21 at 8 57 40 pm](https://cloud.githubusercontent.com/assets/4276638/7265522/36454462-e869-11e4-8ba5-42fcc0fbc629.png)
