### ISSUE TITLE
Bentley doesn't have push access

### ISSUE THREAD

**Issue by ajm188** [hacsoc/the_jolly_advisor#65]
We should talk about permissions on this repo.

Also there are a ton of teams in the hacsoc org and when I was talking to Tim his position was something to the effect of "I don't know why we have so many teams; I don't think we really use them for anything." So at some point (maybe over the summer), we should get this organization actually organized. Then giving bentley access should be easy and not jankily just adding one more person to the repo.

**Comment by ajm188** [comment]
Temporarily adding him to the jolly advisor team. Will reorg after finals.

@matthewbentley you should have push access now.

**Comment by matthewbentley** [comment]
This seems to be fixed. Can we close this?

**Comment by StephHippo** [comment]
Yeah if you say it's fixed, it's fixed.
