### ISSUE TITLE
Allow production database host and port to be set via env var

### ISSUE THREAD

**Issue by matthewbentley** [hacsoc/the_jolly_advisor#70]
Try to get the host and port for the database each from a environment variable; if env vars dont exist then use a sane default (127.0.0.1:5432).

This will make deployment a bit easier, so the app and the database can go in different docker containers.

**Comment by ajm188** [comment]
Going to propose this waits until after the team gets through their senior project presentations. I might get to this tomorrow, otherwise, later.

**Comment by matthewbentley** [comment]
Closed via #77
