### ISSUE TITLE
Use Ruby 2.2.2?

### ISSUE THREAD

**Issue by matthewbentley** [hacsoc/the_jolly_advisor#71]
Not a huge issue, but deploys will be easier with the most recent Ruby version (that is, Ruby 2.2.2 rather than 2.2.0).

Please close this issue if this would take more than ~15 minutes.

**Comment by ajm188** [comment]
2.2.2 is completely backwards compatible with 2.2.0, so this shouldn't be a problem.

The 2.2.2 release info can be found [here](https://www.ruby-lang.org/en/news/2015/04/13/ruby-2-2-2-released/).

**Comment by StephHippo** [comment]
This is cool. I thought 2.2.2 was still in preview. I didn't realize it had been released.

**Comment by matthewbentley** [comment]
Closed by #77
