### ISSUE TITLE
Searching without Autocomplete

### ISSUE THREAD

**Issue by thomasrussellmurphy** [hacsoc/the_jolly_advisor#85]
When searching in the top bar's `Course Select` text box, if the user doesn't interact with the autocomplete and presses `return`, they should be sent to a search with the text they just entered as the query term.
Current behavior: the page reloads when `return` is pressed and the text disappears from the `Course Select` box.

**Comment by ajm188** [comment]
Partially resolved by #93

**Comment by ajm188** [comment]
Partially resolved by #101. We now have 2 of our 3 autocomplete bars not requiring users to actually pick from the autocomplete menu. Only one missing is on the scheduler page, which is going to be a bit more complicated.

**Comment by ajm188** [comment]
Still missing the scheduler portion. Looks like my commit message was a bit aggressive with the issue-closing. I'll give it a stern talking-to.
